### ISSUE TITLE
golang/go did not match import path code.google.com/p/go.net/websoket

### ISSUE THREAD

**Issue by lifala71** [mattn/livestyle-vim#13]
hi

my problem is that the command

`go get code.google.com/p/go.net/websoket`

return

`package code.google.com/p/go.net/websoket: unrecognized import path "code.google.com/p/go.net/websoket" (parse https://code.google.com/p/go.net/websoket?go-get=1: no go-import meta tags (meta tag github.com/golang/go did not match import path code.google.com/p/go.net/websoket))`

i use manjaro
neovim with rafi/vim-config

**Comment by mattn** [comment]
Fixed README.md
