### ISSUE TITLE
Not working on Vim 7.4

### ISSUE THREAD

**Issue by kuntau** [mattn/livestyle-vim#6]
Here is what I got when try to start livestyled manually

```bash
localhost: ~/.vim/bundle/livestyle-vim/livestyled                                                             
→ ./livestyled
2013/08/26 06:17:41 listen tcp <nil>:54000: address already in use
```

**Comment by DemonCloud** [comment]
@mattn 
.. I got LiveStyle issue

![2015-06-19_134945](https://cloud.githubusercontent.com/assets/7436361/8247879/2cf5f056-168a-11e5-91e8-0890af600a2a.png)


With:

Python 2.7.10 x86

Golang 1.4.2 x86

Win7 Ultimate 32

Gvim 7.4 with Lua Python

**Comment by mattn** [comment]
probably you don't build livestyled/livestyled.go

**Comment by mattn** [comment]
This issue is running duplicate server.
